<?php

namespace App\Imports;

use App\Models\Catalog;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class CatalogImport implements ToModel, WithHeadingRow
{
    /**
     * @param array $row
     *
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function model(array $row)
    {
        return new Catalog([
            'id',
            'unq_id' => $row['unq_id'],
            'category' => $row['category'],
            'sub_category' => $row['sub_category'],
            'discontinued' => $row['discontinued'],
            'legacy_brand' => $row['legacy_brand'],
            'brand' => $row['brand'],
            'mspn' => $row['mspn'],
            'external_id' => $row['external_id'],
            'external_id_type' => $row['external_id_type'],
            'brand_id' => $row['brand_id'],
            'model' => $row['model'],
            'manufacturer' => $row['manufacturer'],
            'lt_p' => $row['lt_p'],
            'size_dimensions' => $row['size_dimensions'],
            'full_size' => $row['full_size'],
            'full_bolt_patterns' => $row['full_bolt_patterns'],
            'full_bolt_pattern_1' => $row['full_bolt_pattern_1'],
            'full_bolt_pattern_2' => $row['full_bolt_pattern_2'],
            'c_z_rated' => $row['c_z_rated'],
            'rft' => $row['rft'],
            'vast_description' => $row['vast_description'],
            'description' => $row['description'],
            'long_description' => $row['long_description'],
            'notes' => $row['notes'],
            'features' => $row['features'],
            'install_time' => $row['install_time'],
            'length_val' => $row['length_val'],
            'section_width' => $row['section_width'],
            'section_width_unit_id' => $row['section_width_unit_id'],
            'aspect_ratio' => $row['aspect_ratio'],
            'rim_diameter' => $row['rim_diameter'],
            'rim_diameter_unit_id' => $row['rim_diameter_unit_id'],
            'overall_diameter' => $row['overall_diameter'],
            'overall_diameter_unit_id' => $row['overall_diameter_unit_id'],
            'weight_tire' => $row['weight_tire'],
            'weight_tire_unit_id' => $row['weight_tire_unit_id'],
            'length_package' => $row['length_package'],
            'length_unit_id' => $row['length_unit_id'],
            'width_package' => $row['width_package'],
            'width_unit_id' => $row['width_unit_id'],
            'height_package' => $row['height_package'],
            'height_unit_id' => $row['height_unit_id'],
            'weight_package' => $row['weight_package'],
            'weight_unit_id' => $row['weight_unit_id'],
            'wheel_finish' => $row['wheel_finish'],
            'simple_finish' => $row['simple_finish'],
            'side_wall_style' => $row['side_wall_style'],
            'load_index_1' => $row['load_index_1'],
            'load_index_2' => $row['load_index_2'],
            'speed_rating' => $row['speed_rating'],
            'load_range' => $row['load_range'],
            'load_rating' => $row['load_rating'],
            'back_spacing' => $row['back_spacing'],
            'offset' => $row['offset'],
            'center_bore' => $row['center_bore'],
            'ply' => $row['ply'],
            'tread_depth' => $row['tread_depth'],
            'tread_depth_unit_id' => $row['tread_depth_unit_id'],
            'rim_width' => $row['rim_width'],
            'rim_width_unit_id' => $row['rim_width_unit_id'],
            'max_rim_width' => $row['max_rim_width'],
            'max_rim_width_unit_id' => $row['max_rim_width_unit_id'],
            'min_rim_width' => $row['min_rim_width'],
            'min_rim_width_unit_id' => $row['min_rim_width_unit_id'],
            'utqg' => $row['utqg'],
            'tread_wear' => $row['tread_wear'],
            'traction' => $row['traction'],
            'temperature' => $row['temperature'],
            'warranty_type' => $row['warranty_type'],
            'warranty_in_miles' => $row['warranty_in_miles'],
            'max_psi' => $row['max_psi'],
            'max_load_lb' => $row['max_load_lb'],
            'image_url_full' => $row['image_url_full'],
            'image_url_quarter' => $row['image_url_quarter'],
            'image_side' => $row['image_side'],
            'image_url_tread' => $row['image_url_tread'],
            'image_kit_1' => $row['image_kit_1'],
            'image_kit_2' => $row['image_kit_2'],
            'season' => $row['season'],
            'tire_type_performance' => $row['tire_type_performance'],
            'car_type' => $row['car_type'],
            'country' => $row['country'],
            'quality_tier' => $row['quality_tier'],
            'construction' => $row['construction'],
            'source' => $row['source'],
            'oem_fitments' => $row['oem_fitments'],
            'status' => $row['status'],
            'msct' => $row['msct'],
            'wheel_diameter' => $row['wheel_diameter'],
            'wheel_width' => $row['wheel_width'],
            'bolt_pattern_1' => $row['bolt_pattern_1'],
            'bolt_circle_diameter_1' => $row['bolt_circle_diameter_1'],
            'bolt_pattern_2' => $row['bolt_pattern_2'],
            'bolt_circle_diameter_2' => $row['bolt_circle_diameter_2'],
        ]);
    }
}
